### PR TITLE
Port to 0.9.2-rc0

### PR DESCRIPTION
**Pull request by Slava**
The start of porting this app to 0.9.2-rc0.

Things those don't work:
- images on front-page
- routing?

These look like Cordova integration bugs but I need to dig into Sous code base a little bit more to be able to fix that.

### CODE REVIEW

**Comment by arbesfeld** [comment]
I think the images on the front page are bugged because absolute paths are used "/*"

**Comment by Slava** [comment]
For some weird reason same branch doesn't work on my home laptop. Going to show it to glasser and claim my reproducible build back.

**Comment by tmeasday** [comment]
I think I was working through the same issues. Strangely w/ the changed image paths, the front page images work:
1. In the iOS sim
2. Across android

but do not work in iOS for real.

Anyway the reason is that IR changes the URL to `file:///` and breaks everything. We need to get IR 0.10.x pre-released I'd say so we can easily use hash URLs.

**Comment by zol** [comment]
@Slava thanks for this. I'm not going to merge it right now as the `cordova` branch is more up to date.

**Comment by Slava** [comment]
Closing this and deleting the branch as Tom Coleman has a different branch with same changes.

**Pull request closed without merging**
